export const PAYMENT_NETWORK_ACTION = "PAYMENT_NETWORK_ACTION";
export const PAYMENT_NUMBER_ACTION = "PAYMENT_NUMBER_ACTION";
export const PAYMENT_STATUS_ACTION = "PAYMENT_STATUS_ACTION";
export const IMAGE_CAPTURE_ACTION = "IMAGE_PREDICTION_ACTION";