/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGarden` | `/gardenManagement/addGarden`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGardenMap` | `/gardenManagement/addGardenMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement` | `/gardenManagement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenResources` | `/gardenResources`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGarden` | `/gardenManagement/addGarden`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGardenMap` | `/gardenManagement/addGardenMap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gardenManagement` | `/gardenManagement`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/gardenResources` | `/gardenResources`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/camera${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gardenManagement/addGarden${`?${string}` | `#${string}` | ''}` | `/gardenManagement/addGarden${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gardenManagement/addGardenMap${`?${string}` | `#${string}` | ''}` | `/gardenManagement/addGardenMap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gardenManagement${`?${string}` | `#${string}` | ''}` | `/gardenManagement${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/gardenResources${`?${string}` | `#${string}` | ''}` | `/gardenResources${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGarden` | `/gardenManagement/addGarden`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement/addGardenMap` | `/gardenManagement/addGardenMap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenManagement` | `/gardenManagement`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/gardenResources` | `/gardenResources`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
